version: '3.9'

services:
    www:
        build: .
        container_name: ddongmy-os
        restart: always
        env_file:
            - .env.production
        ports:
            - '3002:3000'
        volumes:
            # 호스트의 도커 소켓을 컨테이너 안으로 마운트
            - /var/run/docker.sock:/var/run/docker.sock
