apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-app
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: web
          image: ghcr.io/dongmin3891/ddongmy-os:ad2a42d91bb6155946c520e0ba7c0cd5aa37d10b
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
